author: lujingbo # 作者
description: 2b or not 2b
keyword: lujingbo, lujb, javascript
favicon: 

excerpt_link: Read more

menu:
 Home: /
#  Tags: /tags/
#  Archives: /archives/
#  Projects: /project/
#  About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

# comment: false

# gitment config
# gitment_owner: false
# gitment_repo: false
# gitment_oauth_id: false
# gitment_oauth_secret: false

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/973059?v=3&s=460
  description: The end is always near.
  # Links
  weibo_username: false 
  twitter_username: false
  github_username: lujb
  zhihu_username: false
  douban_username: false